### ISSUE TITLE
请问有办法自动保存图片到本地吗

### ISSUE THREAD

**Issue by Achuan-2** [leolee9086/modemkiller#1]
插件导出多图，每次要一张张保存有点麻烦

**Comment by leolee9086** [comment]
有办法

**Comment by leolee9086** [comment]
- [x] https://github.com/leolee9086/modemkiller/issues/3

- [x] https://github.com/leolee9086/modemkiller/issues/2 
这个似乎没有必要，改为下载单个文件

- [x] https://github.com/leolee9086/modemkiller/issues/4 
这个似乎也没必要

- [x] https://github.com/leolee9086/modemkiller/issues/5

**Comment by leolee9086** [comment]
基本上搞完了，明天应该就可以用了，不过注意保存下你自己的页脚标志，这里我目前还不想提供可以配置的地方

**Comment by leolee9086** [comment]
- [x] https://github.com/leolee9086/modemkiller/releases/tag/0.0.6
这个issue我暂时关闭了，你可以帮忙关注一下这个：
https://github.com/leolee9086/modemkiller/issues/8

**Comment by leolee9086** [comment]
感谢反馈

**Comment by Achuan-2** [comment]
感谢
