### ISSUE TITLE
额外新增纯文本导出及自定义背景

### ISSUE THREAD

**Issue by mozhux** [leolee9086/modemkiller#14]
图片分享其实对于那些云笔记来讲，还有一个比较重要的点是能支持纯文本导出同时内置几个好看的模板？
![eb7c41671978bcff388676a3b523e5f](https://github.com/leolee9086/modemkiller/assets/46953371/43a8b104-ab51-403e-995f-c0501bfed737)
![cd02e8417fef511268a2510c2b903fb](https://github.com/leolee9086/modemkiller/assets/46953371/26c44d4f-5472-457a-9b92-ce875bc61363)

**Comment by leolee9086** [comment]
这个不专门支持了，支持自定义导出用css，我希望留一些需要代码配置的地方，给“修改思源”这件事情驱一下魅，本来也不是很难，太傻瓜还有黑箱化了也容易造成一般用户因为没有直观感受无法理解开发者的工作量和困难，这是我从ob还有其他几个支持插件的笔记或者其他软件得来的教训

一定难度的参与性会更好一点

**Comment by leolee9086** [comment]
通过这个issue实现了几乎是我能想到的最花哨且不是很难的导出方式了：  https://github.com/leolee9086/modemkiller/issues/13
 
 可以配合themeEditor降低难度，也可以配合开发者工具提高难度
