### ISSUE TITLE
如何对index.js进行修改，移除图片的水印？

### ISSUE THREAD

**Issue by Ghost-Girls** [leolee9086/modemkiller#15]
31行就这么一句，也没什么修改注释在，这怎么改？
seenIds.add(nodeId);

**Comment by leolee9086** [comment]
https://github.com/leolee9086/modemkiller/blob/master/source/dialogTemplate.js

**Comment by leolee9086** [comment]
readme里面改忘了

**Comment by leolee9086** [comment]
https://github.com/leolee9086/modemkiller/issues/16
