### ISSUE TITLE
期望可以块级别导出不含标题

### ISSUE THREAD

**Issue by mozhux** [leolee9086/modemkiller#9]
如题，希望可以块标增加导出按钮，只导出对应块的。

**Comment by leolee9086** [comment]
![image](https://github.com/leolee9086/modemkiller/assets/19915077/dca3b4fc-805c-4334-9770-d6f6e11cbd14)

**Comment by leolee9086** [comment]
聚焦模式下导出时这里可以控制是否显示文档标题
单个块导出请关注issue

- [x] https://github.com/leolee9086/modemkiller/issues/10
- [x] https://github.com/leolee9086/modemkiller/issues/11

**Comment by leolee9086** [comment]
已经搞定了，issue我先关了，感谢反馈
